name: CI
on:
  pull_request:
  push:
    branches: [dev, main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r infra/env/requirements.txt
          pip install -e .
      - name: Lint
        run: |
          ruff check src tests
          mypy src
      - name: Unit tests
        run: |
          pytest -q --cov=src --cov-report=term-missing
